import React from "react"
import {
  Panel,
  PanelBody,
  MediaBox,
  MediaBoxHeader,
  MediaBoxBody,
  MediaBoxTitle,
  MediaBoxDescription,
} from 'react-weui';

import _ from "lodash";

const DATA = {
  company1: [
    {
      img_src: "https://lh3.googleusercontent.com/eOXYfM4C_CJc6hJ9Yxa0q0Xf-O8u03T5af6NdC5vnuYKLnrgsIjEaM4lUK3Mj7gNn7Y",
      title:"腾讯－微信",
      content:"微信迅速在「看一看」上线了疫情实时动态播报，还设置了「疫区日记」、「权威声音」等版块，发布一线医务人员、重点疫区病患的跟踪报道，为民众提供更加多元的信息资讯。",
      link:"https://mp.weixin.qq.com/s/aSBDFvP8FB3TlY0UfXuV-g"
    },
    {
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"丁香园－丁香医生",
      content:"丁香医生在 1 月 21 日上线了疫情实时播报平台和疫情地图，对疫情的确诊和疑似感染人数进行播报，并每隔一个小时将零散发布的各地卫健委和官方媒体发布的疫情解读和答疑、相关政策及措施进行收集整理，实时更新各地肺炎疫情的最新情况。",
      link:"https://ncov.dxy.cn/ncovh5/view/pneumonia?scene=2&clicktime=1579585220&enterid=1579585220&from=timeline&isappinstalled=0"
    },
    {
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"知乎",
      content:"知乎在APP首页新增「肺炎防治」版块，不仅包含常规的疫情信息与实时播报，还设置了 11 个细分类目，帮助用户了解官方通报、疫区现状、诊疗渠道、捐助方式等多项信息；并优先推送疫情相关的问题与答案，为用户了解疫情、防范肺炎提供切实指引。",
      link:"https://www.zhihu.com/special/19681091"
    },{
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"腾讯－腾讯新闻",
      content:"腾讯新闻较真平台自 1 月 21 日起，与中国医师协会健康传播工作委员会联合上线了「新型冠状病毒肺炎实时辟谣」专题，对在市面上已有传播的信息资讯进行查证和辟谣，截止至 1 月 30 日已辟谣超过 100 条。",
      link:"https://vp.fact.qq.com/home?ADTAG=xw-1.jz&chlid=news_news_top&devid=7cc3fdfd5ab80b44&qimei=862187033020340&uid=&shareto=wx&from=singlemessage&isappinstalled=0"
    },{
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"快手",
      content:"1 月 27 日晚，快手直播答题活动「快手状元」联合国家广播电视总局网络司、国家卫生健康委疾控局和宣传司推出「疫情防控」专场，集中向用户普及防护知识，传递权威信息。",
      link:"https://mp.weixin.qq.com/s/D38p4zUEekr0EuyEMFMFnQ"
    },{
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"腾讯－腾讯医典",
      content:"腾讯医典上线了新型肺炎词条内容，涵盖了从症状、病因、就医、预防等结构化知识；此外，腾讯医典还单独设立了「返程预防」版块，帮助未来返工的民众更科学、更全面地预防肺炎。",
      link:"https://h5.baike.qq.com/mobile/pneumonia.html?adtag=gzh.yd.cd.fygj&state=0&VNK=65865960"
    },{
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"喜马拉雅",
      content:"喜马拉雅 APP 上线了抗肺炎版块，在对疫情进行实时播报和解读的同时，联合武汉市疾病预防控制中心等机构，上线疫情防护相关音频，为用户提供权威性的疫情防护指南。",
      link:"https://mp.weixin.qq.com/s/blKsXX7izS9COoX2P1uA5Q"
    },{
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"平安好医生",
      content:"平安好医生联合武汉市卫生健康委员会开通了抗议电话义诊专线，为公众免费提供新型肺炎咨询、疫情防护指导服务；此外，平安好医生 APP 还开通了 7/24 的新型肺炎为真专区，由呼吸道专家进行实时答疑，判定疑似病例，告知应对措施，避免延误病情。",
      link:"https://mp.weixin.qq.com/s/qABiQ_fYXTw8wf8cjClWZA"
    },{
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"阿里巴巴－阿里健康",
      content:"支付宝在「阿里健康」版块也上线了「阿里健康医生义诊」，不仅包含在线肺炎免费专家诊断，还发起了「应对新冠肺炎心理健康援助行动」，设立心理援助专线，为医护人员和患者提供切实的心理健康援助服务。",
      link:"https://mp.weixin.qq.com/s/jHLLorn8QhTdRypHtopHqA"
    },{
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"腾讯－腾讯健康",
      content:"腾讯健康联合国家卫生健康委宣传司发布了新型冠状病毒感染的肺炎医疗救治定点医院，用户在微信搜一搜中输入「定点医院」即可第一时间获得了解。",
      link:"https://mp.weixin.qq.com/s/OfzFLSPdqdm9zQFboSQI_A"
    },{
      img_src: "http://user-assets.sxlcdn.com/images/310787/Fv-v6jZ6jWMXBUmKvzpJFUDtXFs6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"360",
      content:"360 集团与无糖信息于 1 月 27 日联合开发上线了新型冠状感染性肺炎确诊患者同行查询系统。用户输入行程日期、车次和地区，即可查询是否为已披露有新型肺炎确诊患者同行的火车、飞机和地铁。",
      link:"https://mp.weixin.qq.com/s/Gst2cRJYIM5EwD-bvskc3g"
    },
  ],
  company2:[
    {
      img_src:"https://www.xyzapk.com/wp-content/uploads/2017/11/com.zhihu_.android.jpg.png",
      title:"多个云视频会议产品",
      content:"疫情期间，企业微信、腾讯会议、阿里钉钉、飞书、Zoom、华为 WeLink、苏宁豆芽等产品均为用户免费开放更高的会议人数上限，支持随时随地发起音视频会议。而钉钉和华为 WeLink 在开放视频功能的同时，还上线了「员工健康」服务，建立完整高效的员工健康信息收集系统，实现组织健康管理的在线化、数字化。",
      link:"javascript:void(0);"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"石墨文档",
      content:"石墨文档除了紧急推出疫情时期使用的远程办公版外，还为用户总结出 8 个高频使用的远程办公模板，供用户一键领取并即刻使用。",
      link:"https://mp.weixin.qq.com/s/it4zsbHmnkLinVf9OoDYbA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"金山－WPS文档",
      content:"WPS 开放了可供多人同时协作编辑的在线文档/表格/幻灯片，加急上线了近 600 套写作模板，同时将 WPS 系产品内嵌的异地开会、待办任务安排、文件管理、协作编辑等功能统一整理成文供用户参考。",
      link:"https://mp.weixin.qq.com/s/dEVqSJbtI1jrmUZpCmQ5oQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"印象笔记",
      content:"印象笔记为需要远程办公的中小微企业和团队提供线上办公支持，提供存储、共享、知识管理、信息安全等多项服务。",
      link:"https://mp.weixin.qq.com/s/ov2CkeKDn0pBk5GqoXyF7A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"阿里巴巴－钉钉",
      content:"疫情期间，钉钉发起了「在家上课行动计划」，「在线课堂」功能将免费向全国大中小学开放，可以支持百万学生同时在线上课，覆盖广大农村地区学校，积极响应了教育部「停课不停学」的号召。",
      link:"https://mp.weixin.qq.com/s/OS6t-TLv-IZo7bW9V1_eRw"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"CCtalk",
      content:"CCtalk将在疫情结束前，持续地为个人、老师、教培机构、公立学校提供免费服务，不仅从行动上响应「停课不停学」的号召，还让在特殊时期面临重重困难的线下培训机构和教育工作者服下一颗强有力的定心丸。",
      link:"https://mp.weixin.qq.com/s/3E_mVuoXpqLNpCgaRBYdZQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"维普网、万维网",
      content:"万方、维普网均免费开放了其文献资源。而万方除了免费开放其资源文献外，还进一步开放了其创新助手和科慧服务，为科研人员的分析和项目申报提供充分支持。",
      link:"javascript:void(0);"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"腾讯文档",
      content:"腾讯文档在首页设立了抗击疫情专题，为事业单位、社区、企业、学校等组织提供全方位的疫情相关信息登记模板，帮助不同组织、高校进行信息收集、记录、上报、管理、备份，实现人员管控、捐赠及物资管理等事项的全方位覆盖。",
      link:"https://docs.qq.com/desktop/templates-author.html?author_id=30011"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"问卷星",
      content:"问卷星在问卷库中增设了疫情问卷模板，包括春节返工情况调查、学生返校情况调查、政府疫情信息收集、社区居民健康调查、医疗机构健康调查等内容。",
      link:"https://mp.weixin.qq.com/s/idQGTRL8XoQGZFnsi2kbvw"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FkzHnFpt9oU22DA9IOSA95hgkkao.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"灵析",
      content:"灵析作为一项专业面向公益机构的管理工具，在其表单模板库中迅速上线了疫情防控专题模板，涉及人员信息统计、物资采购登记、志愿者招募统计，全力支持组织用户开展相关信息收集与统计工作。",
      link:"https://mp.weixin.qq.com/s/VNfSEBduIKwF5M-ha1umBA"
    },
  ],
  company3:[
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FjTqw_o_ay25gK2rOkTGmYSnhP_6.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"达达集团",
      content:"达达集团启动“到家新鲜菜场”项目，重点保障京东到家平台每日 7-10 点的蔬菜、水果、肉禽蛋奶、米面粮油、方便速食等生鲜、民生类商品供给，让市民可以足不出户也能安心选购，每天吃上新鲜菜。",
      link:"https://mp.weixin.qq.com/s/YOloLv3en6KqysG7gb2t2A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"益海嘉里",
      content:"从1月1日至2月2日，益海嘉里武汉企业群陆续发运粮油产品共计70809吨，包括食用油55134吨、大米11857吨、挂面2525吨和面粉1293吨等。",
      link:"https://mp.weixin.qq.com/s/lvkFNroVDO8BRv7cXqRZpg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"梅赛德斯奔驰",
      content:"梅德赛斯奔驰开通了免费事故救援热线，并承诺基于疫情的150公里免费拖车与曲松车出租车报销费用。",
      link:"https://mp.weixin.qq.com/s/2TIFZSJXsdntPu9nGcW8tQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"多家电商、物流、餐饮企业",
      content:"1月26日，美团外卖在全国范围率先推出无接触配送服务。随后，盒马、饿了么、每日优鲜、苏宁小店、京东到家、便利蜂等提供配送的平台也都上线了无接触配送服务，通过骑手和用户约定，将商品放置到指定位置，如公司前台、家门口等，减少面对面接触，保障用户和骑手在收餐环节的安全。喜茶、奈雪、肯德基、麦当劳等陆续推出无接触配送方案，并且制作注明出餐经手所有员工的姓名、体温的安心卡，钉在外卖袋上随餐配送。",
      link:"javascript:void(0);"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"融创",
      content:"融创全力实施社区的健康管控措施，除了对所有进出社区人员进行体温测量工作、对异地返城家庭进行逐一排查以外，还针对电梯、休闲设施、垃圾桶、车库等重要公共点位，门把手、快递柜等位置进行清洁消杀，并特别设置了废弃口罩、医疗用品的专用回收处理点，杜绝二次污染。",
      link:"https://mp.weixin.qq.com/s/PcFPYilkXPwdv84VTZp-dQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"美团－美团单车",
      content:"美团单车率先发起“无差别消毒”倡议，并在北京、广州、天津、西安、厦门、珠海、兰州、太原等城市落实“不分你我他”街头单车消毒举措，即运维人员不分品牌，不分颜色，对负责区域内所有共享单车进行消毒。",
      link:"https://mp.weixin.qq.com/s/AJ6URJIDbsZJCZ-M4d4eEA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"滴滴",
      content:"滴滴平台动员司机筹建应急车队，配合指挥部门统一调度。滴滴在全国175个城市启动防疫工作。北京、大连、哈尔滨等71个城市已设立发放防疫物资保障点及消毒站点，为运营网约车提供口罩、防护服等设备，为司机师傅保驾护航。",
      link:"https://mp.weixin.qq.com/s/vJfsLNzLRSHLgIw127ypng"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"一汽大众",
      content:"一汽大众开始提供线上预约及上门去送车，推动“零接触”维保。",
      link:"https://mp.weixin.qq.com/s/C13f59edQQQ6BIaIo6MqHA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"多家地产企业",
      content:"为共击疫情、保障商户利益，万达、融创、龙湖、华润、新城、远洋等超二十家房企对商业地产推出减免租金的举措。其中万达商管集团对全国各地所有万达广场的商户，从1月24日至2月25日内的租金及物业费全免，业内预计万达减免租金或达30亿。",
      link:"javascript:void(0);"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"京东",
      content:"2月2日，京东面向平台25万商家推出了11项补贴支持措施，帮助商家渡过难关。这些措施涵盖了费用减免、金融和物流支持、流量支持、技术支持、健康保障等，如京东健康为商家员工提供免费医生问诊服务、京东数科推出息费减免和延迟还款政策、京东物流对新仓配商家实现一对一服务和48小时急速签约等。",
      link:"https://mp.weixin.qq.com/s/HqsZReRf1eqMwvo5n0QPjg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"盒马",
      content:"2月3日，盒马宣布通过用工转移的方式，引进云海肴、青年餐厅、西贝、茶颜悦色等多家餐饮企业的待业员工，以解决待岗人员的收入问题，并降低餐饮企业暂停营业期间的人力资源成本。",
      link:"https://mp.weixin.qq.com/s/YN6BoXvW80qfsMjPcUIDJQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"京东－京东7FRESH",
      content:"京东7FRESH发布了“人才共享”计划，邀请临时歇业的餐饮、酒店、影线及零售联营商户员工在疫情期间以短期打工的方式加盟，并提供充分的安全保障。",
      link:"https://mp.weixin.qq.com/s/N-jukiB5sIcxIepGmccfow"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"每日优鲜",
      content:"每日优鲜与西贝和眉州东坡两家餐饮企业在人力调配上展开合作，由每日优鲜提供原材料，西贝和眉州东坡提供人力用于加工，三方共同保证疫情期间消费者的食材供应。",
      link:"http://finance.ifeng.com/c/7toXAT1qMFF"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"滴滴－小桔车",
      content:"滴滴出行和小桔车服紧急和湖北省内94家租赁公司伙伴、26家金融保险等机构沟通协商，共同发起倡议行动，武汉、黄冈等湖北16个城市里，从小桔车服合作租赁公司租车的司机无需缴纳2020年2月份的租金，车辆租期顺延一个月。",
      link:"https://mp.weixin.qq.com/s/gzqDdk20xcJl4MyDOr1XPQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"爱库存",
      content:"疫情爆发后，爱库存设立了商家扶持计划，为平台商家提供资源流量支持、工具赋能、资金回笼加速等政策，缓解商家用户的库存压力，以减少疫情对实体销售的巨大影响。",
      link:"https://mp.weixin.qq.com/s/wB5PDgXYnhYXXO2jkz8D9Q"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"爱彼迎",
      content:"爱彼迎在疫情期间成立了专项基金，并在基金支持下，作出包括返还湖北房东服务费、资源扶持及经济补偿等在内的十项承诺。",
      link:"https://mp.weixin.qq.com/s/CqMatM9ifN9eCNMpBMFmVw"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"美的集团",
      content:"由美的集团创立的和的慈善基金会宣部推出“和衷共济”小微企2亿元应急支援计划，采取无偿资助模式，重点支持顺德区内受疫情影响较大的零售、餐饮、住宿、旅游等行业的个体工商户及小微企业，纾缓其在租金、人工等方面的短期资金压力。",
      link:"https://mp.weixin.qq.com/s/w1KzpaDp5n18cCP_MzM5AQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"多家出行旅游平台",
      content:"携程、去哪儿、飞猪、马蜂窝等企业均相应出台免费退改保障政策，为已购买机票、火车票的旅客提供免费退票服务。值得一提的是，携程早在1月23日就推出了“安心取消保障”倡议，呼吁酒店为用户提供免费取消服务，吸引了超过25万家酒店加入倡议。",
      link:"https://mp.weixin.qq.com/s/zyqsdFrMeZMnMeXnpWhtig"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"复星集团",
      content:"复星集团在口罩、防护服的物资援助方面做到了近乎极致。在24日宣部启动全球调配医疗物资计划后，复兴充分发挥其全球化的资源优势，开展全球范围的物质筹措工作，第一时间将物资送往国内疫情防控前线。在计划启动后的第二天，复星便在全球范围内购得近60万件医疗物资，全面体现其超高的资源能力和调配效率。",
      link:"https://mp.weixin.qq.com/s/2E7YtHd8VltQFKDIqNR4cw"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"国家电网",
      content:"疫情发生后，国家电网迅速成立了应对疫情工作领导小组，并发布了支持疫情防控及供电服务的十项举措，包括雷神山及火神山医院的供电建设保障、疫情防治重点机构的供电保障、医护人员集中住宿宾馆用电保障等保障措施，确保医疗工作的顺利有序开展。",
      link:"https://mp.weixin.qq.com/s/DUAJio5BNTiIayZBTt1gyw"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"创维",
      content:"深圳创维-RGB电子有限公司第一时间驰援火神山、雷神山两所疫情防控专业医院。第一批500台病房专用电视，已直接发车运往武汉蔡甸火神山医院。病房专用电视可支持语音操控，可作为看护、远程对话使用，用于医护人员跟病人远程沟通，减少交叉传播风险。",
      link:"https://mp.weixin.qq.com/s/7hMVOGPPYg7xI8dmRYdiQw"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"奇安信",
      content:"作为中国最大的网络安全公司，奇安信在疫情期间，使用其应急协同与指挥平台、 终端杀毒等产品与服务，为全国200多家医疗疾控机构、600多个重要信息系统提供云端实时监测和防御，并为相关网站提供必要的安全防护。",
      link:"https://mp.weixin.qq.com/s/I8KPinx488q1qKUs-JvSiw"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"联想集团",
      content:"疫情发生后，联想集团不仅第一时间成立了疫情防控小组，为武汉火神山医院及雷神山医院免费提供医院所需的IT设备，还迅速招募了志愿工程师并派遣援助队伍，完成千余台设备的安装和调试，并持续进行今后的运维工作。",
      link:"https://mp.weixin.qq.com/s/sSxZ2BPJSiwYar0lo7x78w"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"望海康信",
      content:"望海康信上线“医院应急物资管理平台”，为全国各级医院、物资供应商、公益组织、企事业单位及个人建立快速沟通通道。",
      link:"https://mp.weixin.qq.com/s/TvqVuWfFXPS0fLuArza_uA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"柠檬豆玺品",
      content:"1月27日，柠檬豆玺品开通了覆盖全国范围的15个地区的直播间，展开包括医疗器械、防护用品等在内的零部件原材料供需对接，每个地区都有平均300家企业通过平台直播的形式快速找到生产物资物料，解决生产断档问题，保障武汉防疫设备物资供应。",
      link:"https://mp.weixin.qq.com/s/hLWcdEfx4iOQwsE93mVQqQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"平安集团－平安保险",
      content:"平安健康险发起，平安i康保·公益战疫，优先为奋战在一线的“战士”们，免费提供20万保额的新冠肺炎身故保障金；平安养老险北京、浙江、辽宁、河北、江西等五地分公司，分别为“抗疫”一线的医护人员、公安干警、媒体人等捐赠保险保障，总保额超111亿元；平安产险为全国800万疾控和医护人员无偿提供专属风险保障，人均保额50万元；平安养老险推出了“疫情防控志愿者保障计划”，向15000名全国各地抗击新型冠状病毒肺炎疫情的志愿者提供保险保障。",
      link:"https://mp.weixin.qq.com/s/tkIoJrn6rZoP6ual3oUZ8w"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"滴滴",
      content:"滴滴在武汉市“医护保障车队”已对接7所医院的11个院区的5000余名医务工作者。武汉市“社区保障车队”的1207名司机，为402个社区的2000余名居民提供了出行服务。",
      link:"https://mp.weixin.qq.com/s/L_oTlU14METUkQ9PQAtltA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"多家武汉酒店",
      content:"为给奋斗在抗击疫情一线的医护人员提供免费和方便的住宿，数百位武汉酒店业内人士于1月23日至30日组建了“武汉医护酒店支援联盟”。截至1月30日，联盟合计为6056位医护人员提供超4万个间夜的住宿。",
      link:"https://mp.weixin.qq.com/s/0fp2WglnapOlldcw1V453A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"可口可乐",
      content:"可口可乐基于多年来系统成熟的赈灾机制，充分发挥其装瓶厂、经销商、零售商三方形成的高效网络优势，迅速开展物资保障行动，自1月25日起便与壹基金和云豹救援队为武汉多家医院提供饮用水保障。",
      link:"https://mp.weixin.qq.com/s/ksGtj3RMVzm0rSM6XDVeow"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/Fsnz5I2iarIijW69FGgo8sLfHRKM.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"美团",
      content:"美团在设立医护人员支持关怀专项基金的同时，还联合多家合作商户，向武汉医护人员提供免费送餐服务。",
      link:"https://mp.weixin.qq.com/s/hKV_QCkzmH5dzWQBorlcXQ"
    }
  ],
  company4:[
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FieQrQq-yJCm6XeWvsgBV0I3vgIO.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"阿里巴巴－阿里云、阿里健康",
      content:"阿里云联合支付宝、钉钉推出免费的智能社区疫情防控小程序，可以帮助社区一线工作人员完成出入登记、健康打卡、疫情通知等工作。而且，很快还将与体温贴、AI摄像头、守门贴等智能硬件产品联网，帮助轻松掌握社区出入人员的健康状况。",
      link:"https://mp.weixin.qq.com/s/MDdxm994IKqydThKgRNDcQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"文思海辉",
      content:"为助力园区管理企业做好复工和疫情防控准备工作，文思海辉研发上线了“园钉通”——疫情防控期园区复工后的人员管控解决方案，通过微信小程序实现园区内员工信息的快速认证。",
      link:"https://mp.weixin.qq.com/s/_mlRZyZ1eWwE90B32P8-uA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"袋鼠云",
      content:"袋鼠云数据可视化团队研发出了“员工健康追踪云图”，协助企业、相关部门做好疫情防控与追溯，直至疫情完全结束。“员工健康追踪云图”可帮助企业实现员工健康状况把握、防疫措施和生活工作指南指定、科学实现有序返岗复工等内容。",
      link:"https://mp.weixin.qq.com/s/WAFBjPh53frh30gkxyXTgQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"声智科技",
      content:"声智科技在现有的智能传感技术和人工智能技术基础上，加速研发优化 AI 数字人红外测温系统、电梯AI语音控制方案、AI医疗智能屏等多款非接触式抗疫解决方案，把 AI 技术落地投入到各大城市公共场所的疫情防控管理中。",
      link:"https://mp.weixin.qq.com/s/KkNPs8FNFMaPpEvCXCA5nQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"大疆",
      content:"自疫情发布以来，大疆农业便开始使用植保无人机支持各地抗击疫情。河南宝丰、成都崇州、山东聊城、湖南常德等超过3000个村庄的大疆农业植保队纷纷行动，为村庄及主要街道口喷洒消毒液剂，协助当地消杀防疫。",
      link:"https://mp.weixin.qq.com/s/d0H4Y3HmUUv6iB071H3P-A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"百度－百度飞浆",
      content:"2 月 13 日，百度飞桨宣布开源业界首个口罩人脸检测及分类模型。基于此模型，可以在公共场景检测大量的人脸同时，把佩戴口罩和未佩戴口罩的人脸标注出来，快速识别各类场景中不重视、不注意防护病毒的人，减少公众场合下的安全隐患。",
      link:"https://mp.weixin.qq.com/s/iCz1ls5RV73LEGUJm9Gevg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"京东－京东物流",
      content:"疫情爆发后不久，京东物流就开始了在疫情核心区武汉的智能配送筹备工作。为了实现智能配送常态化，京东物流从各地抽调配送机器人驰援武汉。不仅如此，京东物流还会将 L4 自动驾驶技术与套件对外开放，为生态中其他机器人厂商提供技术支持和升级。",
      link:"https://mp.weixin.qq.com/s/535zRb-_NU4sCH_MOJVRfA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"摄星智能",
      content:"摄星智能通过持续对网络上涌现的各类历史数据进行爬取、汇总、分析、拟合，利用AI算法对经典传染病模型进行细化、调参、优化，设计出可实时更新的疫情峰值预测模型与查询软件，提供最近一个月的肺炎疫情预测数据，辅助政府部门、医护工作者及广大社会群体对各项事务开展合理计划与安排。",
      link:"https://mp.weixin.qq.com/s/9iTYrp_xv70f8JAamN0jVA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"实在智能",
      content:"实在智能开发出“新冠肺炎智能疫情咨询机器人”，具有聊天机器人的交互形态，用户可以通过类似微信聊天的方式，通过口语化的交互向机器人提问。它可以秒级回复用户关心的问题，帮助用户动态掌握有关疫情的最新动态、防护措施、政府举措、辟谣信息等各类资讯。",
      link:"https://mp.weixin.qq.com/s/779D9ZCfDYCeB2PTqp0Gsg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"轻松筹",
      content:"轻松筹所在的轻松公益借助自身强烈的科技属性，在捐赠信息透明度和反馈上给予捐赠人及时的进展公示。作为国内首个公益区块链，轻松筹“阳光链”发挥公开、透明的特性，为公益组织赋能，解决信任难题，提升公益效率。",
      link:"https://mp.weixin.qq.com/s/vC7bdL3JXo7iI4Uja8vqkA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"趣链科技",
      content:"趣链科技于 2 月 10 日正式上线了慈善捐赠溯源平台“善踪”。该平台利用联盟区块链网络，为本次疫情中慈善捐赠提供全链路可信、高效的解决方案，使需求方拥有方便快捷的需求信息发布平台。捐赠方能够顺利完成物资捐赠、受捐方能及时收到捐赠物资、群众则能看见且相信捐赠的全流程。",
      link:"https://mp.weixin.qq.com/s/C5c1-bSs4spSGKRd3tYO2w"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"万向集团－万象区块链",
      content:"万向区块链联合万向信托打造的「万向慈善信托账户管理平台」，基于区块链技术的慈善信托账户管理平台，可帮助捐赠人直接管理账户体系，并能对捐赠人账户的关键文件和资产进行存证，对关键事件的发生时间进行历史溯源等，实现慈善捐赠的公开透明。",
      link:"https://mp.weixin.qq.com/s/3VEJJ80u2LCv4AzLTZCt7w"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"京东－京东城市",
      content:"京东城市开发出“西南禽苗交易信息平台”，部署全国首个“现代农业操作系统”，帮助广汉市构建起现代化智能农业的数字底座为政府经济提振及相关产业扶持政策出台提供数据支撑，提升农业综合效益和产业竞争力。",
      link:"https://mp.weixin.qq.com/s/6ZPOYl8i8y65CTpP5I6G_A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"咪店",
      content:"咪店推出“10万+中小企业造血计划”，免费为零售、餐饮、房产中介等重灾行业、企业员工大于20人的中小企业搭建企业自救SAAS系统，助力企业冲出经营困境。",
      link:"https://mp.weixin.qq.com/s/Il7h3twx06BV_WI3X3r3_A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"顺网科技",
      content:"为缓解全国网吧业主由于暂时关停导致的巨额损失，顺网云网咖即为网吧利用存量电脑（闲置机器）和带宽通过顺网独立研发的云电脑技术（高性能游戏主机云化）向玩家提供服务。对于玩家而言，家中只要有一台普通电脑，就可以通过云端调用附近网吧的专业游戏主机，此举将大大缓解疫情对网吧经营带来的巨大影响。",
      link:"https://mp.weixin.qq.com/s/dNi2xcPLsJLSFZjIzrtn7A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"京东",
      content:"抗击疫情期间，为了确保防护物资和民生类商品的价格稳定，京东通过技术和人工结合的手段，24小时不间断地进行商品价格的监控与治理，严格管控平台商品价格。",
      link:"https://mp.weixin.qq.com/s/4QO8dHENFqOm9JSPTsRYBQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"恒安嘉新",
      content:"2月3日，恒安嘉新公安业务团队与反诈团队全力配合北京刑侦总队，对全国抗疫期间所发生的一批涉疫情特殊诈骗案件进行了相关技术分析，案情分析初步方向确定后，恒安嘉新团队同步配合警队就涉疫案情进行远程沟通，全力配合公安机关保障疫情期间人民财产安全。",
      link:"https://mp.weixin.qq.com/s/rngbxv6dx8MrQ78OYkX-4g"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"百度－百度地图慧眼",
      content:"百度地图慧眼迁徙大数据通过数据定向、分析等途径确定了500万人员流出的方向。在1月1日至1月26日期间，武汉人员迁出地前十排行多为孝感、黄冈等省内市区。通过百度迁徙，用户可以对全国乃至省市每天迁入迁出流动进行分析。在直观的可视图下，地方可以对疫情控制进行更加精准和严格的控制。",
      link:"https://mp.weixin.qq.com/s/w3OAyknCP_l1I3yrfRn96g"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"数位科技",
      content:"数位科技通过大数据分析，呈现封城前后武汉市常驻人口走向及对疫情的影响，旨在为地方相关机构决策提供参考。",
      link:"https://mp.weixin.qq.com/s/-atRPSMumALchdp0OrKPoA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"中科曙光",
      content:"中科曙光开发出了疫情排查管理上报系统，此系统运用云计算、大数据分析技术可以充分掌握返乡人员相关数据，多方面多维度进行分析，帮助政府全方位了解人员信息结构，实现快速采集，实时分析，精准上报。",
      link:"https://mp.weixin.qq.com/s/1rkw_5RRmvqAIlrXTK8L5A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"京东－京东云与AI",
      content:"面对猛增的咨询需求，传统的热线电话难以承担重负，互联网平台、AI技术可以有效提升市民咨询应对能力。2月4日，抗“疫”前线武汉市长专线正式开通京东云与AI的“智能疫情助理”。市民访问市长专线，即可快速获得有价值的信息，极大缓解了公共服务的咨询压力，提高了服务响应水平。",
      link:"https://mp.weixin.qq.com/s/FqWR7ko13d7m1ZNUiItCpg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"京东－京东云与AI",
      content:"2月9日，京东“应急公共服务平台”上线北京市海淀区政府网站和公众服务平台。作为智能供应链国家新一代人工智能开放创新平台的重要组成部分——“应急公共服务平台”，由京东云与AI为海淀区政府定制部署，提供“应急物资、疫情动态、企业服务、市民服务”等多重服务，全面支持北京市海淀区应急防疫工作。",
      link:"https://mp.weixin.qq.com/s/RgVPkfkK_eQjfkjf0U-x2g"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"华为",
      content:"华为支撑湖北移动和湖北联通，正式开通蔡甸火神山 5G 基站，整个过程只用了三天时间。除此之外，华为还成立了一支由服务、研发、供应链等组成的特别保障组，确保湖北卫健委视频会议系统正常运行。",
      link:"https://mp.weixin.qq.com/s/c1IZwtwAp8c_l3NabxP9zg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"中科曙光",
      content:"中科曙光向湖北及武汉市定点救治医院捐赠相关计算设备，用于疫情监测、诊治及信息存储等急需场所。同时，中科曙光在武汉当地集结完毕一支 IT 运维应急保障队伍，全力保障湖北地区用户设备稳定高效运行。此外，曙光还特别组建了一支技术团队，全力支持抗灾前线的信息化建设。",
      link:"https://mp.weixin.qq.com/s/DVbkp4F9o00b3Bp2CALEtQ"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"平安－平安医保科技",
      content:"平安医保科技于1月29日驰援湖北省人民医院，定点投放64层移动CT影像车，为身处疫情前线的医护人员及患者提供强有力的诊疗保障。经过远程操作培训，前线医生能够调试并使用影像车及CT设备，实时上传拍片结果连线中心自主研发的远程影像诊断平台“平安好影像”，提供远程阅片与专家在线指导。",
      link:"https://mp.weixin.qq.com/s/8L-C_aJicvXm4Mf638VU8A"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"达闼科技",
      content:"达闼科技携手中国移动为武汉多家医院提供5G云端医护助理机器人、5G云端消毒清洁机器人、5G云端送药服务机器人和5G测温巡查机器人，承担远程看护、测量体温、消毒、清洁和送药等工作，有效减少人员交叉感染、提升病区隔离管控水平。",
      link:"https://mp.weixin.qq.com/s/ECyRyuHIBDeS_bk7hJx8Zg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"优思达",
      content:"优思达基于全自动核酸分析平台紧急开发了全自动POCT新型冠状病毒核酸检测试剂盒，从样本到结果最快30分钟，包括样本处理、核酸提取、核酸扩增和检测。",
      link:"https://mp.weixin.qq.com/s/9TOqQkHnSnTti5flFU1shg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"智云健康",
      content:"智云健康为武汉多家医院提供「智云医汇管理系统+手持一体机」AIoT集成体系，不仅提高了从科室到全院的信息化管理效率，更为医院和医生提供了病患全程管理服务。",
      link:"https://mp.weixin.qq.com/s/U2RlOpaIJ-dh8_JWBy6eYA"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"推想科技",
      content:"推想针对新型冠状病毒肺炎，在淄博定点医院上线了CT+AI产品。在爆发式的疫情面前，这套AI系统能够帮助医生更快速地进行肺炎感染筛查和疫情监测，诸如肺内感染病灶检出、全自动前后片对比和疗效评估等功能，以实现准确治疗评估，避免院内的进一步交叉感染。",
      link:"https://mp.weixin.qq.com/s/fkbvSoIwikzfMNDHXMQImg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"盈创建筑科技",
      content:"盈创建筑科技上海有限公司通过3D打印技术，能够将建筑材料、钢厂的钢渣、沙漠沙作为打印“油墨”，打印出3D打印隔离屋。小屋内部可设置了床位区、盥洗区，配备空调，迅速就能变成可移动、高强度、封闭保温的“疫情隔离屋”。",
      link:"https://mp.weixin.qq.com/s/4T1CYnIOplw3OLzvLdDPNg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"阿里巴巴－阿里云",
      content:"阿里云在 1 月 29 日向全球公共科研机构免费开放一切 AI 算力，以加速本次新型肺炎新药和疫苗研发。阿里云也建立了阿里云疫情公益小组，用于与各科研机构取得联系并实时提供支持。此外，达摩院还已通过 AI 算法，将原来数小时的疑似病例基因分析缩短至半小时，大幅缩短确诊时间，并能精准检测出病毒的变异情况。",
      link:"https://mp.weixin.qq.com/s/0J69z82bZdz5IjsLNgIJvg"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"腾讯－腾讯云",
      content:"截止至目前，腾讯云已经为多家科研机构免费开放云超算等能力，为研究机构的疫苗研发和药物筛选提供稳定高效的算力支持，降低创新药物前期研发的成本与周期。腾讯还在 2 月 3 日发起了「战疫开发者公益联盟」，开放社区上线服务专区，并为参与的服务商和开发者提供资金、云服务资源和技术支持，为各地政府及医疗机构开发疫情服务小程序。",
      link:"https://mp.weixin.qq.com/s/aSBDFvP8FB3TlY0UfXuV-g"
    },
    {
      img_src:"http://user-assets.sxlcdn.com/images/310787/FpHNWgEtbv4cNWQwd3wxtcasRih8.png?imageMogr2/strip/auto-orient/thumbnail/720x1440%3E/quality/90!/format/png",
      title:"京天成",
      content:"京天成抗体研制团队仅用25天，就获得了新型冠状病毒的N蛋白特异单抗，也有多株与SARS和MERS交叉的单抗，并已无偿向130多家相关单位提供了N蛋白兔多抗和夹心法试剂盒，这些单抗将被用于新冠病毒抗原快速检测试剂的开发。",
      link:"https://mp.weixin.qq.com/s/5NHzWJRrxcGYga3-cSla2Q"
    }
  ]
}

class CompanyPanel extends React.Component {
  render () {
    var mediaboxList = _.map(DATA[this.props._class], (company) =>
      {
        return <MediaBox type="appmsg" href={company.link}>
          <MediaBoxHeader><img src={company.img_src}/>
            </MediaBoxHeader>
          <MediaBoxBody>
            <MediaBoxTitle>
              {company.title}
            </MediaBoxTitle>
            <MediaBoxDescription>
              {company.content}
            </MediaBoxDescription>
          </MediaBoxBody>
          </MediaBox>
      }
    )
    return (
      <Panel style={{display: this.props.display}}>
        <PanelBody>
          {mediaboxList}
          <br/><br/><br/>
        </PanelBody>
      </Panel>
    )
  }
}

export default CompanyPanel;